# Generated by Django 6.0.2 on 2026-03-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_bien', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='annonces/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('published', 'Publiée'), ('archived', 'Archivée')], default='pending', max_length=10)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
