# Generated by Django 6.0.2 on 2026-03-17 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_profile_bio_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('prestataire', 'Prestataire (Expert/Artisan)'), ('matiere', 'Matière (Matériaux/Fournitures)')], max_length=20)),
                ('icon_class', models.CharField(default='fa-solid fa-briefcase', help_text='FontAwesome class (ex: fa-helmet-safety)', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise ou service")),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='services/logos/')),
                ('city', models.CharField(default='Casablanca', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('price_start', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='management.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
