# Generated by Django 6.0.2 on 2026-03-26 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_category_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price_start',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('partner', 'Partenaire HCI')], default='client', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='is_boosted',
            field=models.BooleanField(default=False, help_text='Affiche le badge Fusée Orange'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_class',
            field=models.CharField(default='fa-solid fa-cube', help_text='FontAwesome class (ex: fa-helmet-safety)', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Nom de l'entreprise"),
        ),
    ]
