# Generated by Django 6.0.2 on 2026-04-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_fix_missing_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='type_transaction',
            field=models.CharField(choices=[('ACHAT', 'Achat'), ('VENTE', 'Vente'), ('LOCATION', 'Location')], default='ACHAT', max_length=20),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='annonces/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='type_bien',
            field=models.CharField(choices=[('VILLA', 'Villa'), ('APPARTEMENT', 'Appartement'), ('TERRAIN', 'Terrain'), ('BUREAU', 'Bureau')], max_length=50),
        ),
    ]
