# Generated by Django 6.0.2 on 2026-05-07 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_annonce_type_transaction_alter_annonce_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='image',
        ),
        migrations.CreateModel(
            name='AnnonceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='annonces/media/')),
                ('is_video', models.BooleanField(default=False)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='management.annonce')),
            ],
        ),
    ]
