# Generated by Django 6.0.2 on 2026-06-12 19:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_annonce_image_annoncemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoncemedia',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
