# Generated by Django 6.0.2 on 2026-06-19 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_annoncemedia_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='type_transaction',
            field=models.CharField(choices=[('VENTE', 'Vente'), ('LOCATION', 'Location')], default='VENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='BuyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_wanted', models.CharField(choices=[('VILLA', 'Villa'), ('APPARTEMENT', 'Appartement'), ('TERRAIN', 'Terrain'), ('BUREAU', 'Bureau')], max_length=50)),
                ('max_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ville', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
