# Generated by Django 6.0.2 on 2026-07-11 19:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_annonce_type_transaction_buyrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
